name: Norminette Check

on: 
  push:

jobs:
  norminette:
    name: Run Norminette
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Run Norminette
        - name: Run Norminette
        run: |
          OUTPUT=$(norminette)
          echo "$OUTPUT"
          echo "$OUTPUT" | grep -q "Error" && exit 1 || exit 0
